### ISSUE TITLE
Discussion on features

### ISSUE THREAD

**Issue by ctrlaltvikas** [AvocadoNetwork/web#3]
@peter-evans  would like to know if you are open to having more ideas on the desk related to avocado network. I have some ideas related to health care, would like to work with you on this.

**Comment by peter-evans** [comment]
@vikaskyadav Sure. If you have ideas related to Avocado and utility of the AVO token please create issues for your ideas here:
https://github.com/AvocadoNetwork/governance/issues
Thanks!
